heysoft_menu_homepage:
  path: /
  defaults:
      _controller: FrameworkBundle:Redirect:urlRedirect
      path: /categoria/Comida_Del_Dia
      permanent: true

heysoft_menu_categorias:
  prefix: /categoria
  resource: '@HeysoftMenuBundle/Resources/config/routing/categorias.yml'

heysoft_menu_carrito:
  prefix: /carrito
  resource: '@HeysoftMenuBundle/Resources/config/routing/carrito.yml'

heysoft_menu_agregar_carrito:
  path: /carrito/agregar/ajax/call/
  defaults: { _controller: HeysoftMenuBundle:Carrito:agregar }

heysoft_menu_quitar_carrito:
  path: /carrito/quitar/ajax/call/
  defaults: { _controller: HeysoftMenuBundle:Carrito:quitar }

heysoft_menu_eliminar_carrito:
  path: /carrito/eliminar/ajax/call/
  defaults: { _controller: HeysoftMenuBundle:Carrito:eliminar }